### ISSUE TITLE
Wrong publishToAzure() in AzureClient.ino

### ISSUE THREAD

**Issue by andreavalle** [gloveboxes/Arduino-NodeMCU-ESP8266-Secure-Azure-IoT-Hub-Client#2]
Line 169 of AzureClient.ino contains   publishToAzure();
It looks like the wrong syntax, as it's defined as   void publishToAzure(String data, int statusLed)

But I don't understand what should be the parameters here...

**Comment by gloveboxes** [comment]
Hmmm, I wonder if your clone or download got corrupted.  That was an old publishToAzure signature and I just checked and it is void publishToAzure() in publish.ino as it should be.

Can you double check and or re download.  Cheers Dave
