### ISSUE TITLE
Not secure

### ISSUE THREAD

**Issue by haiduc32** [gloveboxes/Arduino-NodeMCU-ESP8266-Secure-Azure-IoT-Hub-Client#4]
By looking into the code I don't see anywhere the CA or at least the thumbprint being specified, which means your communication might be encrypted, but does not validate that the server you're talking to is the actual server you should be talking to => therefor it can not be considered secure.

Can you please explain?

**Comment by gloveboxes** [comment]
Hey there, sorry to take so long to respond, when I wrote this sample it was based on ESP8266 Arduino Lib 2.0 and there was no cert support. That was added at 2.1. By any chance did you get to implement certificate support?  Cheers Dave
